/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelese_app;

import java.awt.Color;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.border.LineBorder;
import java.awt.Color;

public class Dashboard_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_Admins
     */
    public Dashboard_Admin() {
        initComponents();
        setLocationRelativeTo(null);
        loadPaketWisata();
        loadDataTransaksi();
        
        btnSimpan.setBorder(new LineBorder(Color.decode("#00FFCC"), 2));
    
    btnHapus.setBorder(new LineBorder(Color.decode("#00FFCC"), 2));
    btnEdit.setBorder(new LineBorder(Color.decode("#00FFCC"), 2));
    
    btnReset.setBorder(new LineBorder(Color.decode("#00FFCC"), 2));

    // Opsional agar lebih clean
    btnSimpan.setFocusPainted(false);
    btnHapus.setFocusPainted(false);
    btnEdit.setFocusPainted(false);
    btnReset.setFocusPainted(false);
    }
    
    private double ambilHargaPaket(int idPaket) {
        double harga = 0;
        try {
            Connection conn = Database.getConnection();
            String sql = "SELECT harga FROM paket_wisata WHERE id_paket=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, idPaket);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                harga = rs.getDouble("harga");
            }
            rs.close();
            pst.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil harga paket: " + ex.getMessage());
        }
        return harga;
    }
    private int getSelectedIdPaket() {
            String selected = (String) cmbPaketWisata.getSelectedItem();
            if (selected != null && selected.contains(" - ")) {
                return Integer.parseInt(selected.split(" - ")[0]);
            }
            return 0;
        }
    private void hitungTotalHarga() {
        int idPaket = getSelectedIdPaket();
        double hargaPaket = ambilHargaPaket(idPaket);
        int jumlah = 0;
        try {
            jumlah = Integer.parseInt(txtJumlahPeserta.getText());
        } catch (NumberFormatException e) {}
        double total = hargaPaket * jumlah;
        // Tampilkan di field jika mau, contoh:
        lblTotalHarga.setText("Rp " + total); // pastikan ada JLabel lblTotalHarga di desain
    }
    
    private void resetForm() {
        txtNamaPelanggan.setText("");
        txtTelepon.setText("");
        txtJumlahPeserta.setText("");
        lblTotalHarga.setText("Rp 0");
        cmbPaketWisata.setSelectedIndex(0);
        StatusGrup.clearSelection(); // ButtonGroup untuk radio status
    }
                                              
        
  





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatusGrup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNamaPelanggan = new javax.swing.JTextField();
        txtJumlahPeserta = new javax.swing.JTextField();
        cmbPaketWisata = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        rbLunas = new javax.swing.JRadioButton();
        rbBelumBayar = new javax.swing.JRadioButton();
        rbBatal = new javax.swing.JRadioButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDashboard = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTotalHarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 123, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dashboard Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Nama Pelanggan");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Jumlah Peserta");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Paket Wisata");

        txtJumlahPeserta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahPesertaKeyReleased(evt);
            }
        });

        cmbPaketWisata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPaketWisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaketWisataActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Status Pembayaran");

        rbLunas.setText("LUNAS");

        rbBelumBayar.setText("BELUM BAYAR");

        rbBatal.setText("BATAL");

        btnSimpan.setBackground(new java.awt.Color(0, 204, 204));
        btnSimpan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 204, 204));
        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(0, 204, 204));
        btnHapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 204, 204));
        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NO", "Nama Pelanggan", "NO. Telepon", "Jumlah Peserta", "Paket Wisata", "Total Harga", "Status Pembayaran", "Tanggal Pesan", "ID Pemesanan"
            }
        ));
        jScrollPane1.setViewportView(tblDashboard);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("NO. Telepon");
        jLabel6.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jLabel6ComponentRemoved(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Total Harga");

        lblTotalHarga.setText("---");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbBatal)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(rbLunas)
                                    .addComponent(rbBelumBayar))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalHarga)
                                    .addComponent(jLabel5))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNamaPelanggan))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(41, 41, 41))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTelepon)
                                .addGap(31, 31, 31)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtJumlahPeserta, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 107, Short.MAX_VALUE))
                            .addComponent(cmbPaketWisata, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlahPeserta)
                    .addComponent(cmbPaketWisata, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelepon)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbBelumBayar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbBatal))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbLunas)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblTotalHarga)))))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    String namaPelanggan = txtNamaPelanggan.getText().trim();
        String telepon = txtTelepon.getText().trim();
        int idPaket = getSelectedIdPaket();
        int jumlahPeserta;
        double totalHarga;
        String status = "";
        java.sql.Date tanggalPesan = new java.sql.Date(System.currentTimeMillis());

        try {
            jumlahPeserta = Integer.parseInt(txtJumlahPeserta.getText().trim());
            totalHarga = ambilHargaPaket(idPaket) * jumlahPeserta;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah peserta harus angka!");
            return;
        }

        if (rbLunas.isSelected()) status = "LUNAS";
        else if (rbBelumBayar.isSelected()) status = "BELUM BAYAR";
        else if (rbBatal.isSelected()) status = "BATAL";
        else {
            JOptionPane.showMessageDialog(this, "Pilih status pembayaran!");
            return;
        }

        if (namaPelanggan.isEmpty() || telepon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama pelanggan & telepon wajib diisi!");
            return;
        }

        try {
            Connection conn = Database.getConnection();
            String sql = "INSERT INTO dashboard_admin "
                       + "(nama_pelanggan, telepon, id_paket, jumlah_peserta, total_harga, status, tanggal_pesan) "
                       + "VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, namaPelanggan);
            pst.setString(2, telepon);
            pst.setInt(3, idPaket);
            pst.setInt(4, jumlahPeserta);
            pst.setDouble(5, totalHarga);
            pst.setString(6, status);
            pst.setDate(7, tanggalPesan);

            int hasil = pst.executeUpdate();
            if (hasil > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");
                resetForm();
                loadDataTransaksi();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal disimpan!");
            }
            pst.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal simpan data: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    int selectedRow = tblDashboard.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan diedit!");
            return;
        }
        int id = (int) tblDashboard.getValueAt(selectedRow, 0);
        String namaPelanggan = txtNamaPelanggan.getText().trim();
        String telepon = txtTelepon.getText().trim();
        int idPaket = getSelectedIdPaket();
        int jumlahPeserta;
        double totalHarga;
        String status = "";
        java.sql.Date tanggalPesan = new java.sql.Date(System.currentTimeMillis());

        try {
            jumlahPeserta = Integer.parseInt(txtJumlahPeserta.getText().trim());
            totalHarga = ambilHargaPaket(idPaket) * jumlahPeserta;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah peserta harus angka!");
            return;
        }
        if (rbLunas.isSelected()) status = "LUNAS";
        else if (rbBelumBayar.isSelected()) status = "BELUM BAYAR";
        else if (rbBatal.isSelected()) status = "BATAL";
        else {
            JOptionPane.showMessageDialog(this, "Pilih status pembayaran!");
            return;
        }
        try {
            Connection conn = Database.getConnection();
            String sql = "UPDATE dashboard_admin SET nama_pelanggan=?, telepon=?, jumlah_peserta=?, id_paket=?, total_harga=?, status=?, tanggal_pesan=? WHERE id_pemesanan=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, namaPelanggan);
            pst.setString(2, telepon);
            pst.setInt(3, idPaket);
            pst.setInt(4, jumlahPeserta);
            pst.setDouble(5, totalHarga);
            pst.setString(6, status);
            pst.setDate(7, tanggalPesan);
            pst.setInt(8, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diedit.");
            loadDataTransaksi();
            resetForm();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal edit data: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    int selectedRow = tblDashboard.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!");
            return;
        }
        int id = (int) tblDashboard.getValueAt(selectedRow, 0); // kolom pertama = id_pemesanan
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?");
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = Database.getConnection();
                String sql = "DELETE FROM dashboard_admin WHERE id_pemesanan=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
                loadDataTransaksi();
                resetForm();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Gagal hapus data: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void jLabel6ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel6ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6ComponentRemoved

    private void txtJumlahPesertaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahPesertaKeyReleased
    hitungTotalHarga();
    }//GEN-LAST:event_txtJumlahPesertaKeyReleased

    private void cmbPaketWisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaketWisataActionPerformed
    hitungTotalHarga();
    }//GEN-LAST:event_cmbPaketWisataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup StatusGrup;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbPaketWisata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JRadioButton rbBatal;
    private javax.swing.JRadioButton rbBelumBayar;
    private javax.swing.JRadioButton rbLunas;
    private javax.swing.JTable tblDashboard;
    private javax.swing.JTextField txtJumlahPeserta;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables

    private void loadPaketWisata() {
        cmbPaketWisata.removeAllItems();
        try {
            Connection conn = Database.getConnection();
            String sql = "SELECT id_paket, nama_paket FROM paket_wisata";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                cmbPaketWisata.addItem(rs.getInt("id_paket") + " - " + rs.getString("nama_paket"));
            }
            rs.close();
            pst.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal load paket wisata: " + ex.getMessage());
        }
    }


    private void loadDataTransaksi() {
        DefaultTableModel model = (DefaultTableModel) tblDashboard.getModel();
        model.setRowCount(0);
        try {
            Connection conn = Database.getConnection();
            String sql = "SELECT d.id_pemesanan, d.nama_pelanggan, d.telepon, p.nama_paket, d.jumlah_peserta, d.total_harga, d.status, d.tanggal_pesan, d.id_paket "
                        + "FROM dashboard_admin d JOIN paket_wisata p ON d.id_paket = p.id_paket";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id_pemesanan"),
                    rs.getString("nama_pelanggan"),
                    rs.getString("telepon"),
                    rs.getString("nama_paket"),
                    rs.getInt("jumlah_peserta"),
                    rs.getDouble("total_harga"),
                    rs.getString("status"),
                    rs.getDate("tanggal_pesan"),
                    rs.getInt("id_paket")
                };
                model.addRow(row);
            }
            rs.close();
            pst.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + ex.getMessage());
        }
    }
    private void tblDashboardMouseClicked(java.awt.event.MouseEvent evt) {                                          
        int row = tblDashboard.getSelectedRow();
        if (row != -1) {
            txtNamaPelanggan.setText(tblDashboard.getValueAt(row, 1).toString());
            txtTelepon.setText(tblDashboard.getValueAt(row, 2).toString());
            // Cari index paket yang sesuai
            int idPaket = Integer.parseInt(tblDashboard.getValueAt(row, 8).toString());
            for (int i = 0; i < cmbPaketWisata.getItemCount(); i++) {
                if (cmbPaketWisata.getItemAt(i).startsWith(idPaket + " -")) {
                    cmbPaketWisata.setSelectedIndex(i);
                    break;
                }
            }
            txtJumlahPeserta.setText(tblDashboard.getValueAt(row, 4).toString());
            String status = tblDashboard.getValueAt(row, 6).toString();
            if (status.equals("LUNAS")) rbLunas.setSelected(true);
            else if (status.equals("BELUM BAYAR")) rbBelumBayar.setSelected(true);
            else if (status.equals("BATAL")) rbBatal.setSelected(true);
            // Tampilkan total harga
            lblTotalHarga.setText("Rp " + tblDashboard.getValueAt(row, 5).toString());
        }
    }

    // ... sisa kode autogen NetBeans (initComponents dll) ...

}

