/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelese_app;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;
import javax.swing.border.LineBorder;
import java.awt.Color;
public class Paket_Wisata extends javax.swing.JFrame {
    public Paket_Wisata() {
        initComponents();
        setLocationRelativeTo(null);
        setComboBoxValues();
        loadData();               // isi tabel
        cmbLokasi.addActionListener(e -> loadData());
        cmbHarga.addActionListener(e -> loadData());
        btnLihat.addActionListener(e -> lihatDetail());
        btnLihat.setBorder(new LineBorder(Color.decode("#00FFCC"), 2));
    // Opsional agar lebih clean
    btnLihat.setFocusPainted(false);
    }
    // SET PILIHAN COMBOBOX
    private void setComboBoxValues() {
        cmbLokasi.removeAllItems();
        cmbHarga.removeAllItems();
        cmbLokasi.addItem("Semua");

        cmbHarga.addItem("Semua");
        cmbHarga.addItem("Murah");
        cmbHarga.addItem("Mahal");
        
        try {
            Connection conn = Database.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT lokasi FROM paket_wisata");
            while (rs.next()) {
                cmbLokasi.addItem(rs.getString("lokasi"));
            }
            rs.close();
            st.close();
            conn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal memuat lokasi: " + ex.getMessage());
        }
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbLokasi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbHarga = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWisata = new javax.swing.JTable();
        btnLihat = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Beranda = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Paket_Wisata = new javax.swing.JMenuItem();
        Pemesanan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 123, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paket Wisata", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        cmbLokasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLokasiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Lokasi");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Harga");

        cmbHarga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHargaActionPerformed(evt);
            }
        });

        tblWisata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Paket", "Lokasi", "Harga", "Fasilitas"
            }
        ));
        jScrollPane1.setViewportView(tblWisata);

        btnLihat.setBackground(new java.awt.Color(0, 204, 204));
        btnLihat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLihat.setText("Lihat Detail");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(btnLihat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cmbLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLihat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jMenu1.setText("Admin");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Beranda.setText("Beranda");
        Beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BerandaActionPerformed(evt);
            }
        });
        jMenu1.add(Beranda);
        jMenu1.add(jSeparator1);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jMenu1.add(Keluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Wisata");

        Paket_Wisata.setText("Paket Wisata");
        Paket_Wisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Paket_WisataActionPerformed(evt);
            }
        });
        jMenu2.add(Paket_Wisata);

        Pemesanan.setText("Pemesanan");
        Pemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PemesananActionPerformed(evt);
            }
        });
        jMenu2.add(Pemesanan);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BerandaActionPerformed
        Beranda newWin = new Beranda();
        newWin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BerandaActionPerformed

    private void Paket_WisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Paket_WisataActionPerformed
        Paket_Wisata newWin2 = new Paket_Wisata ();
        newWin2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Paket_WisataActionPerformed

    private void PemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PemesananActionPerformed
        Pemesanan newWin3 = new Pemesanan();
        newWin3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PemesananActionPerformed

    private void cmbLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLokasiActionPerformed
    
    }//GEN-LAST:event_cmbLokasiActionPerformed

    private void cmbHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHargaActionPerformed
    
    }//GEN-LAST:event_cmbHargaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
    this.dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paket_Wisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paket_Wisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paket_Wisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paket_Wisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paket_Wisata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Beranda;
    private javax.swing.JMenuItem Keluar;
    private javax.swing.JMenuItem Paket_Wisata;
    private javax.swing.JMenuItem Pemesanan;
    private javax.swing.JButton btnLihat;
    private javax.swing.JComboBox<String> cmbHarga;
    private javax.swing.JComboBox<String> cmbLokasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable tblWisata;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        String lokasiFilter = cmbLokasi.getSelectedItem().toString();
        String hargaFilter = cmbHarga.getSelectedItem().toString();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama Paket");
        model.addColumn("Lokasi");
        model.addColumn("Harga");
        model.addColumn("Fasilitas");

        try {
            Connection conn = Database.getConnection();
            String sql = "SELECT * FROM paket_wisata WHERE 1=1";

            if (!lokasiFilter.equals("Semua")) {
                sql += " AND lokasi = ?";
            }
            
if (hargaFilter != null) {
    if (hargaFilter.equals("Murah")) {
        sql += " AND harga < 1000000";
    } else if (hargaFilter.equals("Sedang")) {
        sql += " AND harga >= 1000000 AND harga < 2000000";
    } else if (hargaFilter.equals("Mahal")) {
        sql += " AND harga >= 2000000";
    }
}


            PreparedStatement pst = conn.prepareStatement(sql);

            if (!lokasiFilter.equals("Semua")) {
                pst.setString(1, lokasiFilter);
            }

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nama_paket"),
                    rs.getString("lokasi"),
                    rs.getDouble("harga"),
                    rs.getString("fasilitas")
                });
            }

            tblWisata.setModel(model);

            rs.close();
            pst.close();
            conn.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + ex.getMessage());
        }
    }

    private void lihatDetail() {
        int row = tblWisata.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data terlebih dahulu.");
            return;
        }

        String nama = tblWisata.getValueAt(row, 0).toString();
        String lokasi = tblWisata.getValueAt(row, 1).toString();
        String harga = tblWisata.getValueAt(row, 2).toString();
        String fasilitas = tblWisata.getValueAt(row, 3).toString();

        JOptionPane.showMessageDialog(this,
            "Paket: " + nama + "\n" +
            "Lokasi: " + lokasi + "\n" +
            "Harga: Rp " + harga + "\n" +
            "Fasilitas: " + fasilitas,
            "Detail Paket",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
}