/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelese_app;
import javax.swing.*;
import java.sql.*;
import javax.swing.border.LineBorder;
import java.awt.Color;
public class Pemesanan extends javax.swing.JFrame {
    public Pemesanan() {
        initComponents();
        setLocationRelativeTo(null);
        setComboBoxHarga();
        loadPaketWisata();

        cmbJenis.addActionListener(e -> loadPaketWisata());
        cmbPaket.addActionListener(e -> updateHarga());
        btnKonfirmasi.addActionListener(e -> simpanPemesanan());
    
        btnBatal.addActionListener(e -> {
        txtNama.setText("");
        txtJumlah.setText("");
        cmbPaket.setSelectedIndex(0);
        lblTotal.setText("Rp0");
    });
        
        btnKonfirmasi.setBorder(new LineBorder(Color.decode("#00FFCC"), 2));
    
    btnBatal.setBorder(new LineBorder(Color.decode("#00FFCC"), 2)); 

    // Opsional agar lebih clean
    btnKonfirmasi.setFocusPainted(false);
    btnBatal.setFocusPainted(false);

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        cmbPaket = new javax.swing.JComboBox<>();
        btnKonfirmasi = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbJenis = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Beranda = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Paket_Wisata = new javax.swing.JMenuItem();
        Pemesanan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 123, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pemesanan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Nama Pemesan");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Jumlah Peserta");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Paket Wisata");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Total Harga");

        lblTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTotal.setText("Rp0");

        cmbPaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnKonfirmasi.setBackground(new java.awt.Color(0, 204, 204));
        btnKonfirmasi.setText("Konfirmasi");
        btnKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(0, 204, 204));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Harga");

        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJenisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTotal)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama)
                            .addComponent(cmbJenis, 0, 146, Short.MAX_VALUE)
                            .addComponent(cmbPaket, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTotal))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jMenu1.setText("Admin");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Beranda.setText("Beranda");
        Beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BerandaActionPerformed(evt);
            }
        });
        jMenu1.add(Beranda);
        jMenu1.add(jSeparator1);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jMenu1.add(Keluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Wisata");

        Paket_Wisata.setText("Paket Wisata");
        Paket_Wisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Paket_WisataActionPerformed(evt);
            }
        });
        jMenu2.add(Paket_Wisata);

        Pemesanan.setText("Pemesanan");
        Pemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PemesananActionPerformed(evt);
            }
        });
        jMenu2.add(Pemesanan);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BerandaActionPerformed
        Beranda newWin = new Beranda();
        newWin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BerandaActionPerformed

    private void Paket_WisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Paket_WisataActionPerformed
        Paket_Wisata newWin2 = new Paket_Wisata ();
        newWin2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Paket_WisataActionPerformed

    private void PemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PemesananActionPerformed
        Pemesanan newWin3 = new Pemesanan();
        newWin3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PemesananActionPerformed

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
    
    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
 
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed

    }//GEN-LAST:event_btnBatalActionPerformed

    private void cmbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJenisActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
    this.dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Beranda;
    private javax.swing.JMenuItem Keluar;
    private javax.swing.JMenuItem Paket_Wisata;
    private javax.swing.JMenuItem Pemesanan;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JComboBox<String> cmbPaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

    

    private void loadPaketWisata() {
        try {
        Connection conn = Database.getConnection();
        String sql = "SELECT nama_paket FROM paket_wisata WHERE 1=1";

        String hargaFilter = (String) cmbJenis.getSelectedItem();
        if (hargaFilter != null) {
            if (hargaFilter.equals("Murah")) {
                sql += " AND harga < 1000000";
            } else if (hargaFilter.equals("Sedang")) {
                sql += " AND harga >= 1000000 AND harga < 2000000";
            } else if (hargaFilter.equals("Mahal")) {
                sql += " AND harga >= 2000000";
            }
        }

        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        cmbPaket.removeAllItems();
        while (rs.next()) {
            cmbPaket.addItem(rs.getString("nama_paket"));
        }

        rs.close();
        st.close();
        conn.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data paket: " + ex.getMessage());
    }
}

        private void updateHarga() {
        try {
        String namaPaket = (String) cmbPaket.getSelectedItem();
        int jumlah = Integer.parseInt(txtJumlah.getText());

        Connection conn = Database.getConnection();
        PreparedStatement pst = conn.prepareStatement("SELECT harga FROM paket_wisata WHERE nama_paket = ?");
        pst.setString(1, namaPaket);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            double harga = rs.getDouble("harga");
            double total = harga * jumlah;

        // Format harga
        java.text.NumberFormat formatRp = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
        lblTotal.setText(formatRp.format(total)); // Contoh: Rp1.500.000,00
        }

        rs.close();
        pst.close();
        conn.close();

        } catch (NumberFormatException ex) {
            lblTotal.setText("Rp0");
        } catch (Exception ex) {
            lblTotal.setText("Gagal hitung");
            JOptionPane.showMessageDialog(this, "Error menghitung harga: " + ex.getMessage());
        }
        }


    private void simpanPemesanan() {
    String nama = txtNama.getText();
    String paket = (String) cmbPaket.getSelectedItem();
    int jumlah;
    double total = 0; // ✅ deklarasi di luar try

    try {
        jumlah = Integer.parseInt(txtJumlah.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah peserta harus angka.");
        return;
    }

    try {
        Connection conn = Database.getConnection();
        PreparedStatement pst1 = conn.prepareStatement("SELECT id_paket, harga FROM paket_wisata WHERE nama_paket=?");
        pst1.setString(1, paket);
        ResultSet rs = pst1.executeQuery();

        if (rs.next()) {
            int idPaket = rs.getInt("id_paket");
            double harga = rs.getDouble("harga");
            total = harga * jumlah;

            PreparedStatement pst2 = conn.prepareStatement(
                "INSERT INTO pemesanan (nama_pemesan, id_paket, jumlah_peserta, total_harga, tanggal_pesan) " +
                "VALUES (?, ?, ?, ?, CURDATE())");

            pst2.setString(1, nama);
            pst2.setInt(2, idPaket);
            pst2.setInt(3, jumlah);
            pst2.setDouble(4, total);
            pst2.executeUpdate();

            pst2.close();
        }

        rs.close();
        pst1.close();
        conn.close();

        // ✅ Panggil form struk dengan total yang valid
        JOptionPane.showMessageDialog(this, "Pemesanan berhasil!");
        new Struk_Pemesanan(nama, paket, jumlah, total).setVisible(true);
        dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());
    }
}


    private void setComboBoxHarga() {
        cmbJenis.removeAllItems();
        cmbJenis.addItem("Semua");
        cmbJenis.addItem("Murah"); // < 1 juta
        cmbJenis.addItem("Sedang");
        cmbJenis.addItem("Mahal"); // >= 1 juta
}
    }

